spring.application.name=backend

# ==========================
# PostgreSQL Configuration
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere
spring.datasource.username=postgres
spring.datasource.password=postgres

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# ==========================
# Server
# ==========================
server.port=8080
server.servlet.session.persistent=false

# ==========================
# Logging
# ==========================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ==========================
# Actuator
# ==========================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always